### PR TITLE
feat: add ability to view solutions in lessons

### PR DESCRIPTION
**Pull request by fsdiogo**
sol

Closes https://github.com/ProtoSchool/protoschool.github.io/issues/89.

### CODE REVIEW

**Comment by fsdiogo** [comment]
## Workflow

solution

**Comment by terichadbourne** [comment]
@fsdiogo Looking good! I pushed a couple of commits to tweak some typos or confusing language I happened to come across while testing and to add instructions for including `_solution` in your Vue file. 

Are you comfortable with "View Solution" being clickable even when you're already viewing the solution, or would you rather make the option disappear or change to non-clickable "Viewing solution" text until the user types something new and the code editor contents no longer match the solution code? This former is what happens with the "Reset code" option, which disappears when the code editor contents match the default code.

**Comment by fsdiogo** [comment]
We were using `_solution` because it was like a private variable and it wasn't used. I switched to `solution` to be streamlined like the `code` one.

**Comment by fsdiogo** [comment]
> Are you comfortable with "View Solution" being clickable even when you're already viewing the solution, or would you rather make the option disappear or change to non-clickable "Viewing solution" text until the user types something new and the code editor contents no longer match the solution code? This former is what happens with the "Reset code" option, which disappears when the code editor contents match the default code.

I'd prefer to always have the option to click the `View Solution`. It doesn't bother me that the `Reset code` is hidden when we have the default code on the screen.

**Comment by terichadbourne** [comment]
@fsdiogo Okay, I'm good to have you merge this if you're feeling ready!  I'll  change `_solution` to `solution` in my MFS tutorials

**Pull request merged**
