### PR TITLE
chore: update project structure - closes #106

### LINKED ISSUE #106: Feature: Landing page / component for each tutorial
Ideally we should have a landing page / component for each tutorial where the lessons are listed out in detail. 

This might live at the route proto.schoo/#/tutorial-title and each lesson would still have a URL like proto.schoo/#/tutorial-title/1

Problems this would solve: 
- Help the user understand how lessons relate to tutorials
- Enable us to link from the "featured tutorials" section of the homepage to the tutorial overview (at the moment they link to the first lesson in the tutorial, which is a bit disorienting, because it's hard to make anchor tags within the tutorials page to drop to the summary) 

A midway improvement would be to create anchors at the top of each tutorial breakdown on the tutorials page, but there's a challenge with how Vue works with anchor tags.

### PR DESCRIPTION
**Pull request by fsdiogo**
I'm proposing a change to the project structure to simplify it and better suit our needs:

```
├── src/
|   └── pages/
|   |   └── ...
|   └── components/
|   |   └── ...
|   └── static/
|   |   └── images/
|   |   └── ...
```

Previously we had full pages inside the `components` folder which I always find a bit strange, so this way we have the main app pages in their own folder and they are populated by importing the atomic components from the `components` folder.

Also created a `static` folder that has everything that is static, such as images, JSON files, etc.

The next step is to _componentize_ the `Tutorials` page to make it a bit more simple. Want me to make a new PR for it or can I make those changes in this one?

### CODE REVIEW

**Comment by fsdiogo** [comment]
- Renamed the `<ExerciseLink>` component to `<LessonLink>`, to be coherent with the `<Lesson>` component.
- Created a `<Tutorial>` component to streamline the logic of adding lessons and simplify the `Tutorials` page.

**Comment by terichadbourne** [comment]
@fsdiogo Do you have ideas on how we could best create landing pages for each tutorial that display the new tutorial component for the appropriate lesson? You've already done a huge chunk of the work requested in #106, but I'm hoping to be able to link to a URL that contains the table of contents for each tutorial, perhaps at the same base URL as the rest of its lessons, minus the `/lesson-number`. We'd make that the new destination for when you click a tutorial card on the homepage or the title of a tutorial (rather than a specific lesson) on the tutorial page.

**Comment by fsdiogo** [comment]
> Do you have ideas on how we could best create landing pages for each tutorial that display the new tutorial component for the appropriate lesson?

One of the reasons I've created the `<Tutorial>` component was to be able to add it to a landing page. Right now all the routes are static, and it's a bit of a pain when adding new lessons, so I'm working to make them as automatic as I possibly can, with my limited Vue knowledge 😇 I'm also simplifying the places/files where the user has to add tutorials.

**Comment by fsdiogo** [comment]
Good news, we now have landing pages for each tutorial 🎉 

Example:

landing

**Comment by fsdiogo** [comment]
Fixed what we talked about in the call:

- renamed the `lessons` folder to `tutorials` 
- added a `featured` flag in the `tutorials.json` to only show the featured tuts in the home page 
- disabled tutorial link in the landing page (that lead to the same page)

Only thing missing is the README update, will do that tomorrow and ping you when this is ready for review!

**Comment by terichadbourne** [comment]
Awesome! 

I just added an issue to fix the link the soon-to-be-broken link to the `chapters.json` file from the chapter organizer documentation once this PR has been merged: https://github.com/ProtoSchool/organizing/issues/44

Also just updated my `file-upload` PR to rename `lessons` directory to `tutorials` and put the boilerplates together in an new folder. A huge chunk of my work there should be applicable when you update the README on this branch. Please take as much as you can from: https://github.com/ProtoSchool/protoschool.github.io/blob/file-upload/README.md

I'll wait on your thumbs up before giving this an official review.

**Comment by fsdiogo** [comment]
@terichadbourne I've updated the README using the one from your WIP PR. Note that I've omitted some things that are on your branch, such as the multiple boilerplates files, but will add them when we merge this one into your.

👀 This is now ready for review!

**Comment by terichadbourne** [comment]
@fsdiogo This looks great! 

I realized that one shortcoming of the way featured tutorials are handled is that the tutorials.json file has to be in the order you want the featured tutorials to show up in on Home.vue, and that the list of all tutorials on Tutorials.vue has to show up in that order as well.

I took a stab at restructuring to add the concept of a "course" in which you can give an index for position of the tutorial within the course, and adjusted computed functions to filter and sort according to the new data available.

I wanted to make this even more reusable by doing this instead: 
`<template v-for="(tutorial, index) in courseTutorials('featured')">

 ```
computed: {
    courseTutorials: function (courseName) {
      return Object.values(tutorialsList).filter(e => e.courses.hasOwnProperty(courseName)).sort((a, b) => a.courses[courseName] - b.courses[courseName])
    }
```

but I couldn't get the right parts of Vue to talk to each other.

Very open to suggestions on how to accomplish the same goal in a more efficient way!

**Comment by terichadbourne** [comment]
@fsdiogo I also made a few small edits to your updated README and deleted one section I believe is no longer necessary thanks to your restructuring. Let me know what you think!

**Comment by fsdiogo** [comment]
@terichadbourne added a `courses.json` to ease ordering (and displaying or hiding) the tutorials and updated the README in regard to that!

**Pull request merged**
