### PR TITLE
Update chapters.json

### PR DESCRIPTION
**Pull request by NukeManDan**
Next steps - `gh-pages` website and twitter account :rocket:

### CODE REVIEW

**Comment by terichadbourne** [comment]
@NukeManDan  Have you by any chance tried running the site on localhost to preview it with your change? The code you submitted looks fine to me and I expected it to work, but the Chapters view isn't loading for me at all when I try to run it from your fork and branch. I'm just staring at a white screen and I have console errors. 

The 'chaptersByRegion' function was previously working with multiple chapters before I deleted the extra dummy data, and it successfully listed regions alphabetically with chapters alphabetically within them. 

I tried deleting extra whitespaces from your `chapters.json` doc and confirmed it passes in a JSON linter. I don't see any formatting differences between this de-whitespaced version of your code that I'm now using: 
```
[
   {
      "name":"ProtoSchool San Francisco",
      "city":"San Francisco, CA",
      "country":"US",
      "region":"North America",
      "organizers":[
         "mikeal"
      ],
      "repo":"http://github.com/protoschool/san-francisco"
   },
   {
     "name":"ProtoSchool Denver",
     "location":"Denver, CO",
     "country":"US",
     "region":"North America",
     "organizers":[
        "NukeManDan"
     ],
     "repo":"http://github.com/protoschool/denver"
   }
]
```
and the formatting of [the dummy data that previously worked](https://github.com/ProtoSchool/protoschool.github.io/blob/ce3ebdb96e0dbfe7873d938e45a1db615cd610c5/src/components/chapters/chapters.json) with this function.

My console in Chrome says: 

```
vue.runtime.esm.js?2b0e:587 [Vue warn]: Error in render: "TypeError: Cannot read property 'localeCompare' of undefined"

found in

---> <Tutorials> at src/components/chapters/Chapters.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js?2b0e:587
logError @ vue.runtime.esm.js?2b0e:1733
globalHandleError @ vue.runtime.esm.js?2b0e:1728
handleError @ vue.runtime.esm.js?2b0e:1717
Vue._render @ vue.runtime.esm.js?2b0e:4542
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
createChildren @ vue.runtime.esm.js?2b0e:5678
createElm @ vue.runtime.esm.js?2b0e:5580
patch @ vue.runtime.esm.js?2b0e:6087
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
init @ vue.runtime.esm.js?2b0e:4133
createComponent @ vue.runtime.esm.js?2b0e:5604
createElm @ vue.runtime.esm.js?2b0e:5551
patch @ vue.runtime.esm.js?2b0e:6126
Vue._update @ vue.runtime.esm.js?2b0e:2656
updateComponent @ vue.runtime.esm.js?2b0e:2784
get @ vue.runtime.esm.js?2b0e:3138
Watcher @ vue.runtime.esm.js?2b0e:3127
mountComponent @ vue.runtime.esm.js?2b0e:2791
Vue.$mount @ vue.runtime.esm.js?2b0e:7995
(anonymous) @ main.js?56d7:66
./src/main.js @ app.js:24083
__webpack_require__ @ app.js:725
fn @ app.js:102
0 @ app.js:24096
__webpack_require__ @ app.js:725
(anonymous) @ app.js:792
(anonymous) @ app.js:795

16:40:42.116 vue.runtime.esm.js?2b0e:1737 TypeError: Cannot read property 'localeCompare' of undefined
    at eval (Chapters.vue?7570:65)
    at Array.sort (<anonymous>)
    at VueComponent.chaptersByRegion (Chapters.vue?7570:65)
    at Watcher.get (vue.runtime.esm.js?2b0e:3138)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:3245)
    at VueComponent.computedGetter [as chaptersByRegion] (vue.runtime.esm.js?2b0e:3503)
    at Object.get (vue.runtime.esm.js?2b0e:1916)
    at eval (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"0ce98071-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/chapters/Chapters.vue?vue&type=template&id=675204af&scoped=true& (app.js:3331), <anonymous>:27:30)
    at Proxy.renderList (vue.runtime.esm.js?2b0e:3701)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"0ce98071-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/chapters/Chapters.vue?vue&type=template&id=675204af&scoped=true& (app.js:3331), <anonymous>:22:17)
```

and a Vue tool in the console shows: 

image

I'm a relative noob, so this is likely my own mistake, but I wonder if you have any guesses as to what's going on.

**Comment by terichadbourne** [comment]
I can resolve the problem by replacing your version of `chapters.json` with this (me using copying and pasting the old dummy data in and replacing it manually with the correct data): 

```
[
   {
      "name":"ProtoSchool San Francisco",
      "city":"San Francisco, CA",
      "country":"US",
      "region":"North America",
      "organizers":[
         "mikeal"
      ],
      "repo":"http://github.com/protoschool/san-francisco"
   },
   {
      "name":"ProtoSchool Denver",
      "city":"Denver, CO",
      "country":"US",
      "region":"North America",
      "organizers":[
         "NukeManDan"
      ],
      "repo":"http://github.com/protoschool/denver"
   }
]
```

which produces: 
image


However, I can't visually see the difference between that and this (me removing whitespaces manually from your code), which *doesn't* render: 

```
[
   {
      "name":"ProtoSchool San Francisco",
      "city":"San Francisco, CA",
      "country":"US",
      "region":"North America",
      "organizers":[
         "mikeal"
      ],
      "repo":"http://github.com/protoschool/san-francisco"
   },
   {
     "name":"ProtoSchool Denver",
     "location":"Denver, CO",
     "country":"US",
     "region":"North America",
     "organizers":[
        "NukeManDan"
     ],
     "repo":"http://github.com/protoschool/denver"
   }
]
```

🤦‍♀️ 

Can you by any chance see the difference here so I can update the chapter setup instructions accordingly?

**Comment by terichadbourne** [comment]
Figured it out. I had "city" (correct) in the table section of the instructions but "location" in the code sample. Just fixed that over there in the organizing repo, and we'll need to use "city" in the Denver entry here.

**Comment by NukeManDan** [comment]
Just getting the same thing solved on my end ! sorry I had to setup a vue dev environment.

**Comment by NukeManDan** [comment]
I also updated and audited the `npm install` to get a few packages updated and updated the package name

**Comment by NukeManDan** [comment]
image

Strange - I get this 50% of the time when updating `chapers.vue` .... Seems to work now. Could oyu try this @terichadbourne ?

**Comment by terichadbourne** [comment]
@NukeManDan I don't get that error in Chrome, Firefox or Safari. I'll go ahead and merge. Thank you!

**Pull request merged**
