### PR TITLE
feat: show logs on ui

### PR DESCRIPTION
**Pull request by fsdiogo**
Surfaces the console logs on to the UI, so user won't have to open their dev tools.

Closes https://github.com/ProtoSchool/protoschool.github.io/issues/182.

### CODE REVIEW

**Comment by fsdiogo** [comment]
We should merge https://github.com/ProtoSchool/protoschool.github.io/pull/111 so people can then branch of `code` and work on features without getting blocked.

To review this you can check commit https://github.com/ProtoSchool/protoschool.github.io/pull/198/commits/23b293a0232138a74b22245ab770e90b9de2f4bf and https://github.com/ProtoSchool/protoschool.github.io/pull/198/commits/f814ce225551bc331c4641fb0d3a3ef859b9ceab, but https://github.com/ProtoSchool/protoschool.github.io/pull/111 has to be merged first.

**Comment by fsdiogo** [comment]
Added syntax highlighting to the outputs:

sh

**Comment by fsdiogo** [comment]
@terichadbourne this is ready for review, can you take a look at the code and the instructions for adding this?

To test you'll have to uncomment the MFS lessons and pass the Lesson 3.

**Comment by terichadbourne** [comment]
@fsdiogo I don't know if it happened in this PR or earlier, but I see this in the standard lesson boilerplate: 
const code = `const CID = require('cids')

const run = async () => {
  /* your code here */
}
return run
`

Can we remove `const CID = require('cids')? The `code` const is what's shown in the exercise box and I'd like it as streamlined as possible. This also looks like something only some authors might need. How else can we get CID functionality accessible without cluttering the editor? (Note that I don't see this line in the file upload boilerplate.)

**Comment by terichadbourne** [comment]
@fsdiogo I made two commits here. 

The first makes it so that it only adds a "step 3" header when it's a file upload lesson, since normal lessons don't have step 1 and step 2 labels. 

The second is a bunch of tweaks to the instructions for developing lessons in general. 

Feel free to merge this PR if my changes look okay to you!

**Comment by fsdiogo** [comment]
> Can we remove const CID = require('cids')?

Yeah, we can remove it AFAIK.

> How else can we get CID functionality accessible without cluttering the editor? 

To get that functionality we only need to pass the modules to the `data`, so we don't need to clutter `code` with that.

```js
const modules = { cids: require('cids') }

export default {
  components: {
    Lesson
  },
  data: () => {
    return { text, validate, code, modules }
  }
}
</script>
```

**Pull request merged**
