### PR TITLE
fix: fix ipfs transpiling

### PR DESCRIPTION
**Pull request by hugomrdias**
this needs ipfs/libp2p to release

needs: 
https://github.com/ipld/js-ipld-dag-pb/pull/121

### CODE REVIEW

**Comment by terichadbourne** [comment]
@hugomrdias Can you say more about "this needs ipfs/libp2p to release"? Do you mean that the code in your ProtoSchool PR is complete but can't be merged until some update is made to the IPFS and libp2p projects to make it work? Or that there's something else we need to do in the ProtoSchool code?

**Comment by hugomrdias** [comment]
@terichadbourne this is still draft when it's ready to review ill add more info

**Comment by terichadbourne** [comment]
@hugomrdias Did the related issue get fixed in the latest release of IPFS or do I have things confused?

**Comment by hugomrdias** [comment]
yes this is all fixed js-ipfs now supports vue without any special config.

**Pull request closed without merging**
