### PR TITLE
feat: rename tutorials

### PR DESCRIPTION
**Pull request by fsdiogo**
TODO:
- [x] Revert the tutorial `002` url from `xxx` back to `basics`
	- [x] main.js
	- [x] tutorials.json
- [x] Comment the line 104 on `main.js`
- [x] Write instructions on the README on how to rename a lesson

Fixes https://github.com/ProtoSchool/protoschool.github.io/issues/289.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@fsdiogo The navbar is broken for me, for example clicking "tutorials" from the nav did tried to go to this: http://localhost:3000/#//tutorials

Cache appears to be updating properly for me when I migrate a URL. 🎉

Have you already looked at whether there's a reasonable way to create redirects in case someone shares an old link?

**Comment by terichadbourne** [comment]
Speaking of redirects, this is interesting....
404 if you try to load something that doesn't exist with no hash in the URL 
image

versus blank page if you try to load the same non-existent thing with a hash 
image

Although ideally we'd do even better and more specific redirects for tutorials whose names have changed, it would be great to also have a backup that defaults any non-existent things to our homepage. I may not have read the Vue documentation correctly the first time around when I did this: 
```js
// 404
  { path: '*', name: '404' }
```

There's redirect documentation here if you have time to take a look: https://router.vuejs.org/guide/essentials/redirect-and-alias.html#redirect

**Comment by fsdiogo** [comment]
> @fsdiogo The navbar is broken for me, for example clicking "tutorials" from the nav did tried to go to this: http://localhost:3000/#//tutorials

Hmm, it's working here. Can you tell me the steps you took?

> Cache appears to be updating properly for me when I migrate a URL. 🎉

Awesome 😎 

> Have you already looked at whether there's a reasonable way to create redirects in case someone shares an old link?

Haven't looked into it yet.

**Comment by fsdiogo** [comment]
> Although ideally we'd do even better and more specific redirects for tutorials whose names have changed, it would be great to also have a backup that defaults any non-existent things to our homepage. I may not have read the Vue documentation correctly the first time around when I did this:

Redirecting a 404 to the home page is easy:

```js
{ path: '*', name: '404', redirect: '/' }
````

Although it's not the best experience having the user write a URL and be redirected to the homepage with no warning whatsoever. It would be best to create a simple 404 page.

**Comment by fsdiogo** [comment]
Added a 404 page when we hit routes that don't exist:

**Comment by fsdiogo** [comment]
Ooops, pushed the 404 page directly to `code` 😅 

I'll revert it and push it here.

**Comment by terichadbourne** [comment]
@fsdiogo I see your note about making the 404 page but not a commit. Have you not yet pushed that? 

> @fsdiogo The navbar is broken for me, for example clicking "tutorials" from the nav did tried to go to this: http://localhost:3000/#//tutorials

> Hmm, it's working here. Can you tell me the steps you took?

1. Open website (localhost:3000/#/)
2. Click on any link in navbar 😂

Once you're inside a specific tutorial, these breadcrumb nav links work: 
image

But I can't find any page from which this main navbar works:
image
It always adds a second slash after the hash like so: 
image

**Comment by fsdiogo** [comment]
Yikes, after restarting the server I'm getting the routes wrong! I'll check what's up.

**Pull request merged**
