### PR TITLE
fix: preserve user code when viewing solution

### PR DESCRIPTION
**Pull request by fsdiogo**
With the lib we're using to render the monaco editor we can't open a new tab nor have a [diff editor](https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example) (this would be the nicer solution IMO).

I've been looking for other vue monaco lib but haven't found any that supports that.

So, another approach I thought about was to toggle another editor (read only) with the solution:

sol

## See it in action

s

There are two problems that can arise: 

- When there's a lot of code in the editor, you'll have to scroll down to view the solution (to overcome this we can automatically scroll to the solution code when pressing the `View Solution` button);
- It may not be clear to the user what gets submitted when you press the `Submit` button;

<hr />

Closes https://github.com/ProtoSchool/protoschool.github.io/issues/211.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@fsdiogo Just confirming that the way this now works, we are never overwriting the content of the code editor automatically, so a user would view the solution visually and then make updates to the code editor on their own, right? Personally I'm happy to force people to do this for a more effective learning experience, but I think it will mess up @olizilla's current plan for automatic testing where the robot clicks "View solution" and then "Submit." Maybe we can teach the robot how to copy and paste? :)

**Comment by fsdiogo** [comment]
> Just confirming that the way this now works, we are never overwriting the content of the code editor automatically, so a user would view the solution visually and then make updates to the code editor on their own, right?

Right on.

> Personally I'm happy to force people to do this for a more effective learning experience

Agree, the other way around you could just mindlessly click `View Solution` and `Submit` without even looking at code, this way you're forced to look at it a bit more.

> but I think it will mess up @olizilla's current plan for automatic testing where the robot clicks "View solution" and then "Submit." Maybe we can teach the robot how to copy and paste? :)

Yes, it will mess with that 🤔 as I'm the one breaking it, I'm up for figuring out a way to solve it 🙃

**Comment by fsdiogo** [comment]
Did some small tweaks to the UI as per the feedback of the Design Weekly Call:

- Positioned `View Solution` (added a chevron to mark that it's expandable) below the user code, so when you click it the solution appears below the button, so the feeling of action-reaction is more obvious
- Aligned `Reset Code` to the left to make code actions coherent and removed the text underline (that seems like a link that will open a new page)

**Comment by terichadbourne** [comment]
@fsdiogo Looking good in terms of placement! I think the arrow behavior pattern that @dzesika was describing on that call, and which I'm familiar with from other sites, is actually a solid triangle that points right when the section is closed/hidden and down when it's open/revealed, like this: 

image

Would that be an easy enough fix to make the UI look more familiar?

**Comment by fsdiogo** [comment]
@terichadbourne here it is:

chev

**Pull request merged**
