### PR TITLE
Add Kelsey Breseman as an organizer

### PR DESCRIPTION
**Pull request by jimcal**
Welcome Kelsey to Seattle chapter organzing team! 🎉

### CODE REVIEW

**Comment by terichadbourne** [comment]
Ooh, it's @frijol of all the awesome UX feedback! 🎉

@frijol Can you please confirm you've reviewed both the [overarching CoC](https://github.com/protoschool/organizing/blob/master/CODE_OF_CONDUCT.md) and the [Phoenix chapter's CoC](https://github.com/ProtoSchool/phoenix/blob/master/CODE_OF_CONDUCT.md) and are comfortable adhering to and enforcing them?

**Comment by terichadbourne** [comment]
On second thought, reviewing the [Seattle CoC](https://github.com/ProtoSchool/seattle/blob/master/CODE_OF_CONDUCT.md) would make a lot more sense. 😂

**Comment by Frijol** [comment]
Yes, I can confirm!

**Comment by terichadbourne** [comment]
Awesome! Just merged this one, but of course you'll want to edit the readme in the Seattle chapter as well. Welcome to the team, @Frijol!

**Pull request merged**
