### PR TITLE
chore: update useful concepts positioning

### PR DESCRIPTION
**Pull request by fsdiogo**
Reposition the `Useful Concepts` box as it was taking a lot of horizontal space from the lesson:

| old | new |
| --- | --- |
| old | new |

### CODE REVIEW

**Comment by olizilla** [comment]
I deliberately pulled out the Useful Concepts box as aside to add a little visual interest, and as the lesson text discusses new concepts, it seemed better to pull the box up near the top, so they can see there is a glossary for those terms.

That said, it looks neat in the example... but perhaps it should just be explained in the body text of the lesson before the term is first used, rather than in a seperate box.

**Comment by terichadbourne** [comment]
I agree with @olizilla that if it’s going to be used it should be an aside visible from the top, not moved to the bottom. However, we could try wrapping the main text so that we’re only losing the right side of the screen until the bottom of the concepts box and then the main text flows all the way to the right again. That would be my proposal for right now. 

See the proposal here for an in-line glossary feature (which we don’t have time to prioritize right now): #99

If we all agree that we don’t want the box used long term, we could remove the option from the instructions for building new tutorials and open an issue (to ignore until after camp) to go back and rewrite existing lessons that use it so they either define terms in line or link to external resources like the decentralized data structure tutorial.

**Comment by fsdiogo** [comment]
What if we put it under the title?

**Comment by terichadbourne** [comment]
@fsdiogo I like your suggestion of putting it at the top, but only for mobile with a very narrow screen. When the space is available, my own preference would be to leave it as an aside at the top right (visible from the top but without any suggestion that it's the main content) and fix the wrapping so that the main content can take up the full width of the screen once it's under the aside (old-school float style). I also think the top of the useful concepts box should be under the lesson title, not aligned with it. Here's a shoddily copy-and-pasted mockup of what I'd envision for when the real estate allows: 
image

**Comment by fsdiogo** [comment]
I like your suggestion @terichadbourne 👍

My last commit addresses everything:

| Desktop | Mobile |
| ------- | ------ |
| desktop | mobile |

What do you think?

**Comment by terichadbourne** [comment]
Looks great @fsdiogo. Thank you!

**Pull request merged**
