### PR TITLE
Extra co-organizers for bangalore chapter

### PR DESCRIPTION
**Pull request by kishansagathiya**

### CODE REVIEW

**Comment by 0zAND1z** [comment]
Hello @terichadbourne ,
We are excited to bring the decentralisation message here, and spread the awareness in Namma Bengaluru!

here are my observations:
> I don't see them listed on your chapter repo yet.

Listing seems to be updated: https://github.com/protoschool/bangalore#organizers Please let us know if we need to update it elsewhere.

> Please note that all new organizers will need to agree to abide by and enforce the Code of Conduct

Is there a CLA-like agreement to be signed? It'll be great if you can shed some more light on how this must be arranged.

> you'll likely need to update your CoC to reflect new options for reporting CoC violations

I have made changes and created a PR for the same: https://github.com/ProtoSchool/bangalore/pull/7. Kindly advise.

Cc @kishansagathiya @vasa-develop

**Comment by terichadbourne** [comment]
> Listing seems to be updated: https://github.com/protoschool/bangalore#organizers Please let us know if we need to update it elsewhere.

Looks great!

> Is there a CLA-like agreement to be signed? It'll be great if you can shed some more light on how this must be arranged.

Nope, just need written confirmation here from @vasa-develop and @0zAND1z that you've reviewed the CoC and are comfortable abiding by and enforcing it. (@kishansagathiya already confirmed this before I set up the repo originally. Thanks!

> I have made changes and created a PR for the same: ProtoSchool/bangalore#7. Kindly advise.

Looks good to me! Thank you for updating.

**Comment by 0zAND1z** [comment]
>Nope, just need written confirmation here from @vasa-develop and @0zAND1z that you've reviewed the CoC and are comfortable abiding by and enforcing it. (@kishansagathiya already confirmed this before I set up the repo originally. Thanks!


@0zAND1z (myself) created the PR updating the COC in https://github.com/ProtoSchool/bangalore/pull/7
I am okay with the details.

@vasa-develop has reviewed the same PR. Vaibhav can you confirm if your contact details in COC are correct?

**Comment by terichadbourne** [comment]
@vasa-develop just confirming you've reviewed your chapter's CoC and are comfortable adhering to and enforcing it?

**Comment by vasa-develop** [comment]
> @vasa-develop just confirming you've reviewed your chapter's CoC and are comfortable adhering to and enforcing it?

Sure. I(@vasa-develop) have reviewed CoC of BLR Chapter of ProtoSchool and I am comfortable adhering to and enforcing it.

**Pull request merged**
