### PR TITLE
Feature: support multiple projects

### PR DESCRIPTION
**Pull request by zebateira**
This PR adds support for multiple projects by adding a new `projects.json` file. Worked on top of #329 PR. 
Current projects supported:

 - IPFS
 - IPLD
 - libp2p
 - Multiformats

### CODE REVIEW

**Comment by zebateira** [comment]
The current issue with the long project name is:


image

**Comment by terichadbourne** [comment]
The functionality is working great for me but I agree it won't work visually like this. :) 

Of the two options you suggested, I prefer Option 1 because it presents the project name in writing and doesn't rely on logo recognition. 
image
It also has the benefit of working naturally on mobile, which would close #371. 

A third option would be to use Option 1 on smaller screens, but pull the logo out bigger to the left on bigger screens (as it is now and in Option 2), leaving just the project title as shown above.

**Comment by zebateira** [comment]
> A third option would be to use Option 1 on smaller screens, but pull the logo out bigger to the left on bigger screens (as it is now and in Option 2), leaving just the project title as shown above.

Here you go

## Option 3

Branch: https://github.com/ProtoSchool/protoschool.github.io/tree/feat/support-multiple-projects-option-3

### Desktop

<div>


</div>

### Small devices

<div>


</div>

**Comment by zebateira** [comment]
IMO I prefer Option 3 if it wasn't for the disconnect between the logo and the project name. Having said that, I prefer Option 2.
Which one do you prefer @terichadbourne ?

**Comment by terichadbourne** [comment]
Option 2 is a no go for me because the project title isn't spelled out anywhere. My first choice is Option 3 (because the logo placement in the big version feels a little less cluttered to me, although I take your point about the logo being separated from the project title) and second choice his Option 1.

**Comment by zebateira** [comment]
@terichadbourne oh sorry, typo on my part. My preference is option 1, not 2.

**Comment by mishmosh** [comment]
Option 3 makes the most sense to me, but perhaps with the project name _above_ the lesson name to preserve hierarchy.

**Comment by terichadbourne** [comment]
Based on feedback from some design peers, we'll plan to go with Option 3 with the following modifications: 

- Set the project name in the site font (Avenir), not in the logotype. The symbol serves as the logo, in this case, so we don’t need two logos.
- Run the project name above the tutorial title, as a running head, essentially. It’ll look better, and it also makes more sense from an IA standpoint (eg Anatomy of a CID is a Multiformats tutorial, so Multiformats goes first).

**Comment by terichadbourne** [comment]
Latest commit moves project name above tutorial and adjusts spacing accordingly. 

Fullscreen:

image

Mobile:

**Pull request merged**
