### PR TITLE
feat: add markdown to outputs

### PR DESCRIPTION
**Pull request by fsdiogo**
Add markdown support for both the success and fail messages, so you can do whatever:

| old | crazy stuff you can do now |
| --- | --- |
| a | c |

### CODE REVIEW

**Comment by terichadbourne** [comment]
@fsdiogo Thanks for adding this feature!

There's not enough difference between these two shades of red for me to quickly tell one part is different from another: 
image

I tried flipping it to a success message and I can't see the contrast in the greens well enough either: 
image

Is there an easy way for you to change those colors so the formatting of code is more visible?

**Comment by terichadbourne** [comment]
I also noticed that you changed some of the cypress code. Do you need me to run those tests as well?

**Comment by fsdiogo** [comment]
> Is there an easy way for you to change those colors so the formatting of code is more visible?

Yeah I can easily tweak the colors. Do you have any suggestion?

> I also noticed that you changed some of the cypress code. Do you need me to run those tests as well?

No need, I just removed unused data-attributes.

**Comment by terichadbourne** [comment]
Since the text is white, I think we should probably either switch the background to a much darker red/green for the code sections or perhaps switch it to a dark gray if that doesn't work?

**Comment by fsdiogo** [comment]
Nice!

Pining to cluster is failing but as we can't trigger the build I'm going to merge this now and wait for cluster to be OK again to then merge https://github.com/ProtoSchool/protoschool.github.io/pull/224 and deploy these two PRs together.

**Pull request merged**
